# Generated by Django 3.1.3 on 2020-12-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usersession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lock',
        ),
    ]
