# Generated by Django 3.1.3 on 2020-11-28 21:13

import accountancy.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('registered', models.BooleanField(default=True)),
            ],
            bases=(accountancy.mixins.AuditMixin, models.Model),
        ),
        migrations.CreateModel(
            name='VatTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=3)),
                ('header', models.PositiveIntegerField()),
                ('line', models.PositiveIntegerField()),
                ('ref', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('field', models.CharField(choices=[('g', 'Goods'), ('v', 'Vat'), ('t', 'Total')], max_length=2)),
                ('tran_type', models.CharField(choices=[('pp', 'Payment'), ('pr', 'Refund'), ('pi', 'Invoice'), ('pc', 'Credit Note'), ('nj', 'Journal'), ('sp', 'Receipt'), ('sr', 'Refund'), ('si', 'Invoice'), ('sc', 'Credit Note'), ('cp', 'Payment'), ('cr', 'Receipt')], max_length=10)),
                ('vat_type', models.CharField(choices=[('i', 'Input'), ('o', 'Output')], max_length=2)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('goods', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controls.period')),
                ('vat_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vat.vat')),
            ],
            options={
                'permissions': [('view_transactions_enquiry', 'Can view transactions')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalVat',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('registered', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical vat',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='vattransaction',
            constraint=models.UniqueConstraint(fields=('module', 'header', 'line', 'field'), name='vat_unique_batch'),
        ),
    ]
