# Generated by Django 3.0.7 on 2020-06-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vat',
            name='name',
            field=models.CharField(default='Standard Rate', max_length=30),
            preserve_default=False,
        ),
    ]
