# Generated by Django 3.1.1 on 2020-10-18 09:58

import accountancy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VatTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=3)),
                ('header', models.PositiveIntegerField()),
                ('line', models.PositiveIntegerField()),
                ('value', accountancy.models.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ref', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=6)),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('field', models.CharField(choices=[('g', 'Goods'), ('v', 'Vat'), ('t', 'Total')], max_length=2)),
                ('tran_type', models.CharField(choices=[('pp', 'Payment'), ('pr', 'Refund'), ('pi', 'Invoice'), ('pc', 'Credit Note'), ('nj', 'Journal'), ('sp', 'Receipt'), ('sr', 'Refund'), ('si', 'Invoice'), ('sc', 'Credit Note'), ('cp', 'Payment'), ('cr', 'Receipt')], max_length=10)),
                ('vat_type', models.CharField(choices=[('i', 'Input'), ('o', 'Output')], max_length=2)),
            ],
            bases=(models.Model, accountancy.models.Audit),
        ),
        migrations.DeleteModel(
            name='HistoricalVat',
        ),
        migrations.AddConstraint(
            model_name='vattransaction',
            constraint=models.UniqueConstraint(fields=('module', 'header', 'line', 'field'), name='vat_unique_batch'),
        ),
    ]
