# Generated by Django 3.0.7 on 2020-07-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vat', '0002_vat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vat',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
