# Generated by Django 3.1.1 on 2020-10-18 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vat', '0002_auto_20201018_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='vattransaction',
            name='vat_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vat.vat'),
        ),
        migrations.AddField(
            model_name='vattransaction',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
