# Generated by Django 3.1.1 on 2020-10-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vat', '0003_auto_20201018_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vattransaction',
            name='value',
        ),
        migrations.AddField(
            model_name='vattransaction',
            name='goods',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vattransaction',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
