# Generated by Django 3.1.2 on 2020-10-25 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vat', '0005_historicalvattransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalVatTransaction',
        ),
    ]
