# Generated by Django 3.1.3 on 2020-12-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuePosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('c', 'cashbook'), ('n', 'nominals'), ('p', 'purchases'), ('s', 'sales')], max_length=1)),
            ],
        ),
    ]
