# Generated by Django 3.1.3 on 2020-12-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0002_queueposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialyear',
            name='number_of_periods',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='historicalfinancialyear',
            name='number_of_periods',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
