# Generated by Django 3.1.3 on 2020-12-27 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0003_auto_20201221_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['fy_and_period']},
        ),
        migrations.CreateModel(
            name='ModuleSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_book_period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_book_period', to='controls.period')),
                ('nominals_period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominals_period', to='controls.period')),
                ('purchases_period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases_period', to='controls.period')),
                ('sales_period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_period', to='controls.period')),
            ],
        ),
    ]
