# Generated by Django 3.0.7 on 2020-06-09 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nominals', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=20)),
                ('goods', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('vat', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('due', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateField()),
                ('due_date', models.DateField()),
                ('type', models.CharField(choices=[('p', 'Payment'), ('i', 'Invoice'), ('c', 'Credit Note'), ('r', 'Refund'), ('bp', 'Brought Forward Payment'), ('bi', 'Brought Forward Invoice'), ('bc', 'Brought Forward Credit Note'), ('br', 'Brought Forward Refund')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseMatching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('matched_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_by_these', to='purchases.PurchaseHeader')),
                ('matched_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_to_these', to='purchases.PurchaseHeader')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.PurchaseHeader')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
                ('nominal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominals.Nominal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='purchaseheader',
            name='matched_to',
            field=models.ManyToManyField(through='purchases.PurchaseMatching', to='purchases.PurchaseHeader'),
        ),
        migrations.AddField(
            model_name='purchaseheader',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.Supplier'),
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('purchases.purchaseheader',),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('purchases.purchaseheader',),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('purchases.purchaseheader',),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('purchases.purchaseheader',),
        ),
    ]
