# Generated by Django 3.1.3 on 2021-01-01 15:00

import accountancy.fields
import accountancy.mixins
import accountancy.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import purchases.models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nominals', '0001_initial'),
        ('contacts', '0001_initial'),
        ('controls', '0001_initial'),
        ('cashbook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vat', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=20)),
                ('goods', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vat', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('due', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('c', 'cleared'), ('v', 'void')], default='c', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('pbi', 'Brought Forward Invoice'), ('pbc', 'Brought Forward Credit Note'), ('pbp', 'Brought Forward Payment'), ('pbr', 'Brought Forward Refund'), ('pp', 'Payment'), ('pr', 'Refund'), ('pi', 'Invoice'), ('pc', 'Credit Note')], max_length=3)),
                ('cash_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashbook.cashbook')),
            ],
            options={
                'permissions': [('view_transactions_enquiry', 'Can view transactions'), ('view_age_creditors_report', 'Can view aged creditors report'), ('create_brought_forward_invoice_transaction', 'Can create brought forward invoice'), ('create_brought_forward_credit_note_transaction', 'Can create brought forward credit note'), ('create_brought_forward_payment_transaction', 'Can create brought forward payment'), ('create_brought_forward_refund_transaction', 'Can create brought forward refund'), ('create_invoice_transaction', 'Can create invoice'), ('create_credit_note_transaction', 'Can create credit note'), ('create_payment_transaction', 'Can create payment'), ('create_refund_transaction', 'Can create refund'), ('edit_brought_forward_invoice_transaction', 'Can edit brought forward invoice'), ('edit_brought_forward_credit_note_transaction', 'Can edit brought forward credit note'), ('edit_brought_forward_payment_transaction', 'Can edit brought forward payment'), ('edit_brought_forward_refund_transaction', 'Can edit brought forward refund'), ('edit_invoice_transaction', 'Can edit invoice'), ('edit_credit_note_transaction', 'Can edit credit note'), ('edit_payment_transaction', 'Can edit payment'), ('edit_refund_transaction', 'Can edit refund'), ('view_brought_forward_invoice_transaction', 'Can view brought forward invoice'), ('view_brought_forward_credit_note_transaction', 'Can view brought forward credit note'), ('view_brought_forward_payment_transaction', 'Can view brought forward payment'), ('view_brought_forward_refund_transaction', 'Can view brought forward refund'), ('view_invoice_transaction', 'Can view invoice'), ('view_credit_note_transaction', 'Can view credit note'), ('view_payment_transaction', 'Can view payment'), ('view_refund_transaction', 'Can view refund'), ('void_brought_forward_invoice_transaction', 'Can void brought forward invoice'), ('void_brought_forward_credit_note_transaction', 'Can void brought forward credit note'), ('void_brought_forward_payment_transaction', 'Can void brought forward payment'), ('void_brought_forward_refund_transaction', 'Can void brought forward refund'), ('void_invoice_transaction', 'Can void invoice'), ('void_credit_note_transaction', 'Can void credit note'), ('void_payment_transaction', 'Can void payment'), ('void_refund_transaction', 'Can void refund')],
            },
            bases=(purchases.models.ModuleTransactions, accountancy.mixins.AuditMixin, accountancy.models.TransactionBase, models.Model),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contacts.contact',),
        ),
        migrations.CreateModel(
            name='PurchaseMatching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('value', accountancy.fields.AccountsDecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('matched_by_type', models.CharField(choices=[('pbi', 'Brought Forward Invoice'), ('pbc', 'Brought Forward Credit Note'), ('pbp', 'Brought Forward Payment'), ('pbr', 'Brought Forward Refund'), ('pp', 'Payment'), ('pr', 'Refund'), ('pi', 'Invoice'), ('pc', 'Credit Note')], max_length=3)),
                ('matched_to_type', models.CharField(choices=[('pbi', 'Brought Forward Invoice'), ('pbc', 'Brought Forward Credit Note'), ('pbp', 'Brought Forward Payment'), ('pbr', 'Brought Forward Refund'), ('pp', 'Payment'), ('pr', 'Refund'), ('pi', 'Invoice'), ('pc', 'Credit Note')], max_length=3)),
                ('matched_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_by_these', to='purchases.purchaseheader')),
                ('matched_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_to_these', to='purchases.purchaseheader')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controls.period')),
            ],
            options={
                'abstract': False,
            },
            bases=(accountancy.mixins.AuditMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('goods', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vat', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type', models.CharField(choices=[('pbi', 'Brought Forward Invoice'), ('pbc', 'Brought Forward Credit Note'), ('pbp', 'Brought Forward Payment'), ('pbr', 'Brought Forward Refund'), ('pp', 'Payment'), ('pr', 'Refund'), ('pi', 'Invoice'), ('pc', 'Credit Note')], max_length=3)),
                ('goods_nominal_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_good_line', to='nominals.nominaltransaction')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchaseheader')),
                ('nominal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nominals.nominal')),
                ('total_nominal_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_total_line', to='nominals.nominaltransaction')),
                ('vat_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vat.vat', verbose_name='Vat Code')),
                ('vat_nominal_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_vat_line', to='nominals.nominaltransaction')),
                ('vat_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_line_vat_transaction', to='vat.vattransaction')),
            ],
            options={
                'ordering': ['line_no'],
            },
            bases=(purchases.models.ModuleTransactions, accountancy.mixins.AuditMixin, accountancy.models.TransactionBase, models.Model),
        ),
        migrations.AddField(
            model_name='purchaseheader',
            name='matched_to',
            field=models.ManyToManyField(through='purchases.PurchaseMatching', to='purchases.PurchaseHeader'),
        ),
        migrations.AddField(
            model_name='purchaseheader',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controls.period'),
        ),
        migrations.AddField(
            model_name='purchaseheader',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.supplier'),
        ),
        migrations.CreateModel(
            name='HistoricalPurchaseMatching',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateField(blank=True, editable=False)),
                ('value', accountancy.fields.AccountsDecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('matched_by_type', models.CharField(choices=[('pbi', 'Brought Forward Invoice'), ('pbc', 'Brought Forward Credit Note'), ('pbp', 'Brought Forward Payment'), ('pbr', 'Brought Forward Refund'), ('pp', 'Payment'), ('pr', 'Refund'), ('pi', 'Invoice'), ('pc', 'Credit Note')], max_length=3)),
                ('matched_to_type', models.CharField(choices=[('pbi', 'Brought Forward Invoice'), ('pbc', 'Brought Forward Credit Note'), ('pbp', 'Brought Forward Payment'), ('pbr', 'Brought Forward Refund'), ('pp', 'Payment'), ('pr', 'Refund'), ('pi', 'Invoice'), ('pc', 'Credit Note')], max_length=3)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('matched_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchases.purchaseheader')),
                ('matched_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchases.purchaseheader')),
                ('period', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='controls.period')),
            ],
            options={
                'verbose_name': 'historical purchase matching',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPurchaseLine',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('line_no', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('goods', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vat', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type', models.CharField(choices=[('pbi', 'Brought Forward Invoice'), ('pbc', 'Brought Forward Credit Note'), ('pbp', 'Brought Forward Payment'), ('pbr', 'Brought Forward Refund'), ('pp', 'Payment'), ('pr', 'Refund'), ('pi', 'Invoice'), ('pc', 'Credit Note')], max_length=3)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('goods_nominal_transaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nominals.nominaltransaction')),
                ('header', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchases.purchaseheader')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nominal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nominals.nominal')),
                ('total_nominal_transaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nominals.nominaltransaction')),
                ('vat_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vat.vat', verbose_name='Vat Code')),
                ('vat_nominal_transaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nominals.nominaltransaction')),
                ('vat_transaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vat.vattransaction')),
            ],
            options={
                'verbose_name': 'historical purchase line',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPurchaseHeader',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ref', models.CharField(max_length=20)),
                ('goods', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vat', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('due', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('c', 'cleared'), ('v', 'void')], default='c', max_length=2)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('type', models.CharField(choices=[('pbi', 'Brought Forward Invoice'), ('pbc', 'Brought Forward Credit Note'), ('pbp', 'Brought Forward Payment'), ('pbr', 'Brought Forward Refund'), ('pp', 'Payment'), ('pr', 'Refund'), ('pi', 'Invoice'), ('pc', 'Credit Note')], max_length=3)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cash_book', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cashbook.cashbook')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='controls.period')),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchases.supplier')),
            ],
            options={
                'verbose_name': 'historical purchase header',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
