# Generated by Django 3.0.7 on 2020-06-17 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vat', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseline',
            name='vat_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vat.Vat'),
        ),
    ]
