# Generated by Django 3.1.2 on 2020-10-25 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('purchases', '0002_auto_20201018_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsupplier',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='HistoricalSupplier',
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contacts.contact',),
        ),
    ]
