# Generated by Django 3.1.3 on 2020-11-19 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_auto_20201101_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseheader',
            options={'permissions': [('create_brought_forward_invoice', 'Create Brought Forward Invoice')]},
        ),
    ]
