# Generated by Django 3.0.7 on 2020-06-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchaseline_vat_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseline',
            old_name='amount',
            new_name='goods',
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
