# Generated by Django 3.0.7 on 2020-06-17 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vat', '0001_initial'),
        ('purchases', '0003_auto_20200617_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseline',
            name='goods',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='vat_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vat.Vat', verbose_name='Vat Code'),
        ),
    ]
