# Generated by Django 3.1.3 on 2020-11-19 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_auto_20201119_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseheader',
            options={'permissions': [('create_brought_forward_invoice', 'Can create brought forward invoice'), ('create_brought_forward_credit_note', 'Can create brought forward credit note'), ('create_brought_forward_payment', 'Can create brought forward payment'), ('create_brought_forward_refund', 'Can create brought forward refund'), ('create_invoice', 'Can create invoice'), ('create_credit_note', 'Can create credit note'), ('create_payment', 'Can create payment'), ('create_refund', 'Can create refund')]},
        ),
    ]
