# Generated by Django 3.0.7 on 2020-06-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_auto_20200617_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseheader',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
