# Generated by Django 3.0.7 on 2020-07-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_auto_20200621_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='code',
            field=models.CharField(default='ab', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseheader',
            name='type',
            field=models.CharField(choices=[('bi', 'Brought Forward Invoice'), ('bc', 'Brought Forward Credit Note'), ('i', 'Invoice'), ('c', 'Credit Note'), ('bp', 'Brought Forward Payment'), ('br', 'Brought Forward Refund'), ('p', 'Payment'), ('r', 'Refund')], max_length=2),
        ),
    ]
