# Generated by Django 3.0.7 on 2020-07-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_auto_20200707_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseline',
            options={'ordering': ['line_no']},
        ),
        migrations.AddField(
            model_name='purchaseheader',
            name='period',
            field=models.CharField(default='202007', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasematching',
            name='period',
            field=models.CharField(default=202007, max_length=6),
            preserve_default=False,
        ),
    ]
