# Generated by Django 3.0.7 on 2020-07-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_auto_20200713_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseheader',
            name='status',
            field=models.CharField(choices=[('c', 'cleared'), ('v', 'void')], default='c', max_length=2),
        ),
    ]
