# Generated by Django 3.0.7 on 2020-07-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0009_purchaseheader_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseheader',
            name='type',
            field=models.CharField(choices=[('pbi', 'Brought Forward Invoice'), ('pbc', 'Brought Forward Credit Note'), ('pi', 'Invoice'), ('pc', 'Credit Note'), ('pbp', 'Brought Forward Payment'), ('pbr', 'Brought Forward Refund'), ('pp', 'Payment'), ('pr', 'Refund')], max_length=3),
        ),
    ]
