# Generated by Django 3.0.7 on 2020-07-25 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nominals', '0007_auto_20200725_1727'),
        ('purchases', '0011_auto_20200725_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseline',
            name='nominal_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nominals.NominalTransaction'),
        ),
    ]
