# Generated by Django 3.0.7 on 2020-07-26 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nominals', '0009_auto_20200726_1121'),
        ('purchases', '0012_auto_20200725_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseline',
            name='nominal_transaction',
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='goods_nominal_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_good_line', to='nominals.NominalTransaction'),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='vat_nominal_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_vat_line', to='nominals.NominalTransaction'),
        ),
    ]
