# Generated by Django 3.0.7 on 2020-07-29 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vat', '0003_auto_20200712_1303'),
        ('items', '0001_initial'),
        ('nominals', '0010_auto_20200727_2009'),
        ('purchases', '0013_auto_20200726_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseline',
            name='goods_nominal_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_good_line', to='nominals.NominalTransaction'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.Item'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='nominal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nominals.Nominal'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='vat_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vat.Vat', verbose_name='Vat Code'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='vat_nominal_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_vat_line', to='nominals.NominalTransaction'),
        ),
    ]
