# Generated by Django 3.0.7 on 2020-07-30 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0002_cashbook_nominal'),
        ('purchases', '0014_auto_20200729_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseheader',
            name='cash_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashbook.CashBook'),
        ),
    ]
