# Generated by Django 3.0.8 on 2020-08-03 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nominals', '0010_auto_20200727_2009'),
        ('purchases', '0016_purchaseline_total_nominal_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseline',
            name='goods_nominal_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_good_line', to='nominals.NominalTransaction'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='total_nominal_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_total_line', to='nominals.NominalTransaction'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='vat_nominal_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_vat_line', to='nominals.NominalTransaction'),
        ),
    ]
