# Generated by Django 3.1.1 on 2020-09-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0017_auto_20200803_2048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditNote',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default='duh', max_length=254),
            preserve_default=False,
        ),
    ]
