# Generated by Django 3.1.1 on 2020-09-23 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0019_supplier_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
    ]
