# Generated by Django 3.1.3 on 2021-01-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnominalheader',
            name='type',
            field=models.CharField(choices=[('nj', 'Journal'), ('nbf', 'Nominal Brought Forward')], max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalnominalline',
            name='type',
            field=models.CharField(choices=[('nj', 'Journal'), ('nbf', 'Nominal Brought Forward')], max_length=3),
        ),
        migrations.AlterField(
            model_name='nominalheader',
            name='type',
            field=models.CharField(choices=[('nj', 'Journal'), ('nbf', 'Nominal Brought Forward')], max_length=3),
        ),
        migrations.AlterField(
            model_name='nominalline',
            name='type',
            field=models.CharField(choices=[('nj', 'Journal'), ('nbf', 'Nominal Brought Forward')], max_length=3),
        ),
        migrations.AlterField(
            model_name='nominaltransaction',
            name='type',
            field=models.CharField(choices=[('pp', 'Payment'), ('pr', 'Refund'), ('pi', 'Invoice'), ('pc', 'Credit Note'), ('nj', 'Journal'), ('nbf', 'Nominal Brought Forward'), ('sp', 'Receipt'), ('sr', 'Refund'), ('si', 'Invoice'), ('sc', 'Credit Note'), ('cp', 'Payment'), ('cr', 'Receipt')], max_length=10),
        ),
    ]
