# Generated by Django 3.1.1 on 2020-10-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominals', '0002_auto_20201018_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnominalheader',
            name='vat_type',
            field=models.CharField(blank=True, choices=[('i', 'Input'), ('o', 'Output')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='nominalheader',
            name='vat_type',
            field=models.CharField(blank=True, choices=[('i', 'Input'), ('o', 'Output')], max_length=2, null=True),
        ),
    ]
