# Generated by Django 3.1.3 on 2020-12-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominals', '0002_auto_20201226_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnominal',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nominal',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='nominal',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='nominal_unique'),
        ),
    ]
