# Generated by Django 3.0.7 on 2020-07-20 19:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nominals', '0002_auto_20200719_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominaltransactions',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 20, 19, 56, 27, 497118, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nominaltransactions',
            name='ref',
            field=models.CharField(default='qaz', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nominaltransactions',
            name='type',
            field=models.CharField(choices=[('pbi', 'Brought Forward Invoice'), ('pbc', 'Brought Forward Credit Note'), ('pi', 'Invoice'), ('pc', 'Credit Note'), ('pbp', 'Brought Forward Payment'), ('pbr', 'Brought Forward Refund'), ('pp', 'Payment'), ('pr', 'Refund'), ('nj', 'Journal')], default='pi', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nominalheader',
            name='type',
            field=models.CharField(choices=[('nj', 'Journal')], max_length=2),
        ),
    ]
