# Generated by Django 3.1.3 on 2020-11-19 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominals', '0002_auto_20201101_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nominalheader',
            options={'permissions': [('create_journal', 'Can create journal'), ('edit_journal', 'Can edit journal'), ('view_journal', 'Can view journal'), ('void_journal', 'Can void journal')]},
        ),
    ]
