# Generated by Django 3.0.7 on 2020-07-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominals', '0003_auto_20200720_1956'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='nominaltransactions',
            name='unique_batch',
        ),
        migrations.AddField(
            model_name='nominaltransactions',
            name='header',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nominaltransactions',
            name='line',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nominaltransactions',
            name='type',
            field=models.CharField(choices=[('pbi', 'Brought Forward Invoice'), ('pbc', 'Brought Forward Credit Note'), ('pbp', 'Brought Forward Payment'), ('pbr', 'Brought Forward Refund'), ('pp', 'Payment'), ('pr', 'Refund'), ('pi', 'Invoice'), ('pc', 'Credit Note'), ('nj', 'Journal')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='nominaltransactions',
            constraint=models.UniqueConstraint(fields=('module', 'header', 'line'), name='unique_batch'),
        ),
    ]
