# Generated by Django 3.1.3 on 2020-11-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominals', '0003_auto_20201119_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nominalheader',
            options={'permissions': [('view_transactions_enquiry', 'Can view transactions'), ('view_trial_balance_report', 'Can view trial balance report'), ('create_journal_transaction', 'Can create journal'), ('edit_journal_transaction', 'Can edit journal'), ('view_journal_transaction', 'Can view journal'), ('void_journal_transaction', 'Can void journal')]},
        ),
    ]
