# Generated by Django 3.1.2 on 2020-10-25 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominals', '0003_auto_20201020_1926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalNominalTransaction',
        ),
    ]
