# Generated by Django 3.0.7 on 2020-07-25 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0010_auto_20200720_1956'),
        ('nominals', '0004_auto_20200725_1649'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NominalTransactions',
            new_name='NominalTransaction',
        ),
    ]
