# Generated by Django 3.0.7 on 2020-07-25 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nominals', '0005_auto_20200725_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominalline',
            name='nominal_transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nominals.NominalTransaction'),
            preserve_default=False,
        ),
    ]
