# Generated by Django 3.0.7 on 2020-07-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominals', '0007_auto_20200725_1727'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='nominaltransaction',
            name='unique_batch',
        ),
        migrations.AddField(
            model_name='nominaltransaction',
            name='field',
            field=models.CharField(choices=[('g', 'Goods'), ('v', 'Vat')], default='g', max_length=2),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='nominaltransaction',
            constraint=models.UniqueConstraint(fields=('module', 'header', 'line', 'field'), name='unique_batch'),
        ),
    ]
