# Generated by Django 3.0.7 on 2020-07-26 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nominals', '0008_auto_20200726_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominalline',
            name='nominal_transaction',
        ),
        migrations.AddField(
            model_name='nominalline',
            name='goods_nominal_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nominal_good_line', to='nominals.NominalTransaction'),
        ),
        migrations.AddField(
            model_name='nominalline',
            name='vat_nominal_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nominal_vat_line', to='nominals.NominalTransaction'),
        ),
    ]
