# Generated by Django 3.0.7 on 2020-07-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominals', '0009_auto_20200726_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominaltransaction',
            name='field',
            field=models.CharField(choices=[('g', 'Goods'), ('v', 'Vat'), ('t', 'Total')], max_length=2),
        ),
    ]
