# Generated by Django 3.0.8 on 2020-08-03 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nominals', '0010_auto_20200727_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominalline',
            name='goods_nominal_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominal_good_line', to='nominals.NominalTransaction'),
        ),
        migrations.AlterField(
            model_name='nominalline',
            name='vat_nominal_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominal_vat_line', to='nominals.NominalTransaction'),
        ),
    ]
