# Generated by Django 3.0.7 on 2020-07-12 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('vat', '0003_auto_20200712_1303'),
        ('nominals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPurchaseHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=20)),
                ('goods', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('due', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(choices=[('bi', 'Brought Forward Invoice'), ('bc', 'Brought Forward Credit Note'), ('i', 'Invoice'), ('c', 'Credit Note'), ('bp', 'Brought Forward Payment'), ('br', 'Brought Forward Refund'), ('p', 'Payment'), ('r', 'Refund')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestPurchaseMatching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('matched_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_by_these', to='accountancy.TestPurchaseHeader')),
                ('matched_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_to_these', to='accountancy.TestPurchaseHeader')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestPurchaseLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('goods', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountancy.TestPurchaseHeader')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
                ('nominal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nominals.Nominal')),
                ('vat_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vat.Vat', verbose_name='Vat Code')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='testpurchaseheader',
            name='matched_to',
            field=models.ManyToManyField(through='accountancy.TestPurchaseMatching', to='accountancy.TestPurchaseHeader'),
        ),
        migrations.AddField(
            model_name='testpurchaseheader',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountancy.TestSupplier'),
        ),
        migrations.CreateModel(
            name='TestCreditNote',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accountancy.testpurchaseheader',),
        ),
        migrations.CreateModel(
            name='TestInvoice',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accountancy.testpurchaseheader',),
        ),
        migrations.CreateModel(
            name='TestPayment',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accountancy.testpurchaseheader',),
        ),
        migrations.CreateModel(
            name='TestRefund',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accountancy.testpurchaseheader',),
        ),
    ]
