# Generated by Django 3.1.1 on 2020-09-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('address', 'address_2', 'city', 'county', 'post_code'), name='unique_address'),
        ),
    ]
