# Generated by Django 3.1.1 on 2020-09-23 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0020_remove_supplier_address'),
        ('sales', '0005_remove_customer_address'),
        ('accountancy', '0002_auto_20200923_2036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
