# Generated by Django 3.1.3 on 2020-11-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='financial_year',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='historicalfinancialyear',
            name='financial_year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
