# Generated by Django 3.1.3 on 2020-11-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='value',
            field=models.CharField(max_length=4),
        ),
    ]
