# Generated by Django 3.1.3 on 2020-11-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20201127_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialyear',
            old_name='value',
            new_name='financial_year',
        ),
        migrations.RenameField(
            model_name='period',
            old_name='value',
            new_name='period',
        ),
    ]
