# Generated by Django 3.1.3 on 2020-11-28 13:55

from django.db import migrations, models
import settings.validators


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20201128_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='financial_year',
            field=models.PositiveSmallIntegerField(validators=[settings.validators.is_fy_year]),
        ),
        migrations.AlterField(
            model_name='historicalfinancialyear',
            name='financial_year',
            field=models.PositiveSmallIntegerField(validators=[settings.validators.is_fy_year]),
        ),
    ]
