# Generated by Django 3.1.3 on 2020-11-28 17:03

from django.db import migrations, models
import settings.validators


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20201128_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='financial_year',
            field=models.PositiveSmallIntegerField(unique=True, validators=[settings.validators.is_fy_year]),
        ),
        migrations.AlterField(
            model_name='historicalfinancialyear',
            name='financial_year',
            field=models.PositiveSmallIntegerField(db_index=True, validators=[settings.validators.is_fy_year]),
        ),
    ]
