# Generated by Django 3.1.3 on 2020-11-27 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20201127_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='month_end',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
