# Generated by Django 3.1.3 on 2020-11-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_period_month_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='period',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
