# Generated by Django 3.1.3 on 2020-11-27 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_historicalfinancialyear_historicalperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='fy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periods', to='settings.financialyear'),
        ),
    ]
