# Generated by Django 3.1.3 on 2020-11-28 21:12

import accountancy.fields
import accountancy.mixins
import accountancy.models
import cashbook.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vat', '__first__'),
        ('nominals', '__first__'),
        ('controls', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('nominal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nominals.nominal')),
            ],
            bases=(accountancy.mixins.AuditMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CashBookHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=20)),
                ('goods', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vat', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('due', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('c', 'cleared'), ('v', 'void')], default='c', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('cbp', 'Brought Forward Payment'), ('cbr', 'Brought Forward Receipt'), ('cp', 'Payment'), ('cr', 'Receipt')], max_length=3)),
                ('vat_type', models.CharField(blank=True, choices=[('i', 'Input'), ('o', 'Output')], max_length=2, null=True)),
                ('cash_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbook.cashbook')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controls.period')),
            ],
            options={
                'permissions': [('view_transactions_enquiry', 'Can view transactions'), ('create_brought_forward_payment_transaction', 'Can create brought forward payment'), ('create_brought_forward_receipt_transaction', 'Can create brought forward receipt'), ('create_payment_transaction', 'Can create payment'), ('create_receipt_transaction', 'Can create receipt'), ('edit_brought_forward_payment_transaction', 'Can edit brought forward payment'), ('edit_brought_forward_receipt_transaction', 'Can edit brought forward receipt'), ('edit_payment_transaction', 'Can edit payment'), ('edit_receipt_transaction', 'Can edit receipt'), ('view_brought_forward_payment_transaction', 'Can view brought forward payment'), ('view_brought_forward_receipt_transaction', 'Can view brought forward receipt'), ('view_payment_transaction', 'Can view payment'), ('view_receipt_transaction', 'Can view receipt'), ('void_brought_forward_payment_transaction', 'Can void brought forward payment'), ('void_brought_forward_receipt_transaction', 'Can void brought forward receipt'), ('void_payment_transaction', 'Can void payment'), ('void_receipt_transaction', 'Can void receipt')],
            },
            bases=(cashbook.models.ModuleTransactionBase, accountancy.mixins.AuditMixin, accountancy.models.TransactionBase, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCashBookLine',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('line_no', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('goods', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vat', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type', models.CharField(choices=[('cbp', 'Brought Forward Payment'), ('cbr', 'Brought Forward Receipt'), ('cp', 'Payment'), ('cr', 'Receipt')], max_length=3)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('goods_nominal_transaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nominals.nominaltransaction')),
                ('header', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cashbook.cashbookheader')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nominal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nominals.nominal')),
                ('total_nominal_transaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nominals.nominaltransaction')),
                ('vat_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vat.vat', verbose_name='Vat Code')),
                ('vat_nominal_transaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nominals.nominaltransaction')),
                ('vat_transaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vat.vattransaction')),
            ],
            options={
                'verbose_name': 'historical cash book line',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCashBookHeader',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ref', models.CharField(max_length=20)),
                ('goods', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vat', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('due', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('c', 'cleared'), ('v', 'void')], default='c', max_length=2)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('type', models.CharField(choices=[('cbp', 'Brought Forward Payment'), ('cbr', 'Brought Forward Receipt'), ('cp', 'Payment'), ('cr', 'Receipt')], max_length=3)),
                ('vat_type', models.CharField(blank=True, choices=[('i', 'Input'), ('o', 'Output')], max_length=2, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cash_book', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cashbook.cashbook')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='controls.period')),
            ],
            options={
                'verbose_name': 'historical cash book header',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCashBook',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nominal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nominals.nominal')),
            ],
            options={
                'verbose_name': 'historical cash book',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CashBookTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=3)),
                ('header', models.PositiveIntegerField()),
                ('line', models.PositiveIntegerField()),
                ('ref', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('field', models.CharField(choices=[('g', 'Goods'), ('v', 'Vat'), ('t', 'Total')], max_length=2)),
                ('type', models.CharField(choices=[('pp', 'Payment'), ('pr', 'Refund'), ('pi', 'Invoice'), ('pc', 'Credit Note'), ('sp', 'Receipt'), ('sr', 'Refund'), ('si', 'Invoice'), ('sc', 'Credit Note'), ('cp', 'Payment'), ('cr', 'Receipt')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cash_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbook.cashbook')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controls.period')),
            ],
        ),
        migrations.CreateModel(
            name='CashBookLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('goods', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vat', accountancy.fields.UIDecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type', models.CharField(choices=[('cbp', 'Brought Forward Payment'), ('cbr', 'Brought Forward Receipt'), ('cp', 'Payment'), ('cr', 'Receipt')], max_length=3)),
                ('goods_nominal_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_book_good_line', to='nominals.nominaltransaction')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbook.cashbookheader')),
                ('nominal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nominals.nominal')),
                ('total_nominal_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_book_total_line', to='nominals.nominaltransaction')),
                ('vat_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vat.vat', verbose_name='Vat Code')),
                ('vat_nominal_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_book_vat_line', to='nominals.nominaltransaction')),
                ('vat_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_book_line_vat_transaction', to='vat.vattransaction')),
            ],
            options={
                'ordering': ['line_no'],
            },
            bases=(cashbook.models.ModuleTransactionBase, accountancy.mixins.AuditMixin, accountancy.models.TransactionBase, models.Model),
        ),
        migrations.AddConstraint(
            model_name='cashbooktransaction',
            constraint=models.UniqueConstraint(fields=('module', 'header', 'line', 'field'), name='cashbook_unique_batch'),
        ),
    ]
