# Generated by Django 3.0.7 on 2020-07-30 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nominals', '0010_auto_20200727_2009'),
        ('cashbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='nominal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nominals.Nominal'),
        ),
    ]
