# Generated by Django 3.1.3 on 2020-11-19 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0002_auto_20201101_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbookheader',
            options={'permissions': [('create_brought_forward_payment', 'Can create brought forward payment'), ('create_brought_forward_receipt', 'Can create brought forward receipt'), ('create_payment', 'Can create payment'), ('create_receipt', 'Can create receipt'), ('edit_brought_forward_payment', 'Can edit brought forward payment'), ('edit_brought_forward_receipt', 'Can edit brought forward receipt'), ('edit_payment', 'Can edit payment'), ('edit_receipt', 'Can edit receipt'), ('view_brought_forward_payment', 'Can view brought forward payment'), ('view_brought_forward_receipt', 'Can view brought forward receipt'), ('view_payment', 'Can view payment'), ('view_receipt', 'Can view receipt'), ('void_brought_forward_payment', 'Can void brought forward payment'), ('void_brought_forward_receipt', 'Can void brought forward receipt'), ('void_payment', 'Can void payment'), ('void_receipt', 'Can void receipt')]},
        ),
    ]
