# Generated by Django 3.1.1 on 2020-10-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0002_auto_20201018_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbookheader',
            name='vat_type',
            field=models.CharField(blank=True, choices=[('i', 'Input'), ('o', 'Output')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='historicalcashbookheader',
            name='vat_type',
            field=models.CharField(blank=True, choices=[('i', 'Input'), ('o', 'Output')], max_length=2, null=True),
        ),
    ]
