# Generated by Django 3.0.8 on 2020-08-31 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nominals', '0011_auto_20200803_2048'),
        ('cashbook', '0002_cashbook_nominal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbookline',
            name='total_nominal_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_book_total_line', to='nominals.NominalTransaction'),
        ),
    ]
