# Generated by Django 3.1.2 on 2020-10-25 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0003_auto_20201021_2020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalCashBookTransaction',
        ),
    ]
