# Generated by Django 3.0.8 on 2020-09-02 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nominals', '0012_auto_20200831_1528'),
        ('cashbook', '0004_auto_20200831_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbookheader',
            name='type',
            field=models.CharField(choices=[('cbp', 'Brought Forward Payment'), ('cbr', 'Brought Forward Receipt'), ('cp', 'Payment'), ('cr', 'Receipt')], max_length=3),
        ),
        migrations.AlterField(
            model_name='cashbookline',
            name='goods_nominal_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_book_good_line', to='nominals.NominalTransaction'),
        ),
        migrations.AlterField(
            model_name='cashbookline',
            name='total_nominal_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_book_total_line', to='nominals.NominalTransaction'),
        ),
        migrations.AlterField(
            model_name='cashbookline',
            name='vat_nominal_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_book_vat_line', to='nominals.NominalTransaction'),
        ),
    ]
