# Generated by Django 3.1.1 on 2020-10-18 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vat', '0003_auto_20201018_1023'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsaleline',
            name='vat_transaction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vat.vattransaction'),
        ),
        migrations.AddField(
            model_name='saleline',
            name='vat_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_line_vat_transaction', to='vat.vattransaction'),
        ),
    ]
