# Generated by Django 3.1.2 on 2020-11-01 12:33

import accountancy.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsalematching',
            name='value',
            field=accountancy.models.AccountsDecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salematching',
            name='value',
            field=accountancy.models.AccountsDecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
